# Use this file if you wish to store AFL credentials securely on Streamlit Community Cloud

[afl]
username = "anthonylasala@hotmail.com"
password = "141021_Buta"

[email]
smtp_server = "smtp.example.com"
smtp_port = 587
from_addr = "your.email@example.com"
to_addr = "anthonylasala@hotmail.com"
subject = "New AFL Replay Downloaded"
